export const Libs = {
  Rxjs: 'rxjs',
  Forms: 'forms',
  SelectionModel: 'selection-model',
  Select: 'select',
  Scroll: 'scroll',
  Tables: 'tables',
  Control: 'control',
  Input: 'input',
  Textarea: 'textarea',
  FormField: 'form-field',
  Dropdown: 'dropdown',
  Cal: 'cal',
  FormError: 'form-error',
  Animations: 'animations',
  Store: 'store',
  Types: 'types',
  Toggle: 'toggle',
};
